### ISSUE TITLE
Sensor always return last queue entry no matter what queue you send to

### ISSUE THREAD

**Issue by axlroden** [StackStorm-Exchange/stackstorm-rabbitmq#4]
Setting:

  rabbitmq_queue_sensor:
    queues:
      - queue1
      - queue2

Will create and consume these queues.
But no matter what queue you are sending messages to, the sensor always returns the last declared queue on the list.

This means I can't make criterias on queue name..

**Comment by LindsayHill** [comment]
Hmm. From a quick skim the code looks like it's **meant** to have the right queue name attached. Something not quite right in there I guess.

**Comment by axlroden** [comment]
I tried playing around with the sensor code, but my python is not good enough to decode this one..

**Comment by LindsayHill** [comment]
I'm no Python expert either. But I'll first try to reproduce it, then I should be able to step through it to figure out what's going on. 

I started trying to put it together yesterday, and ran into some problems related to serialization & payload validation. Might have to play around with my test rig a bit.

**Comment by tienthanh2509** [comment]
Vote, rabbitmq_queue_sensor always return **queue2** in this case

rabbitmq_queue_sensor:
    - "A"
    - "B"
    - "C"
=> trigger.queue = C
